use_frameworks!

platform :ios, '8.0'

target 'TSBezierPathView_Example' do
  pod 'TSBezierPathView', :path => '../'

  target 'TSBezierPathView_Tests' do
    inherit! :search_paths

    # 约束布局
    pod 'Masonry', '~> 1.1.0'
    
  end
end
